### ISSUE TITLE
Parameter type configuration causes issue when filters change input type

### ISSUE THREAD

**Issue by Rarst** [guzzle/guzzle-services#147]
Let's say I have [this parameter configuration](https://github.com/Rarst/wporg-client/blob/36559414bc5248c2812316224f944881d438d222/php/WporgService.php#L160-L167), which worked in 1.0

```php
'request' => [
    'location' => 'formParam',
    'type'     => 'array',
    'filters'  => [
        'Rarst\\Guzzle\\WporgClient::toObject',
        'serialize',
    ],
],
```

As is it started to cause error in 1.1, I think because I _input_ array, but _resulting_ parameter after filters is string:

```
Fatal error: Uncaught GuzzleHttp\Command\Exception\CommandException: Validation errors: [request] must be of type array in C:\server\www\wporg-client\vendor\guzzlehttp\guzzle-services\src\Handler\ValidatedDescriptionHandler.php:76
Stack trace:
#0 C:\server\www\wporg-client\vendor\guzzlehttp\command\src\ServiceClient.php(85): GuzzleHttp\Command\Guzzle\Handler\ValidatedDescriptionHandler->GuzzleHttp\Command\Guzzle\Handler\{closure}(Object(GuzzleHttp\Command\Command))
#1 C:\server\www\wporg-client\vendor\guzzlehttp\command\src\ServiceClient.php(77): GuzzleHttp\Command\ServiceClient->executeAsync(Object(GuzzleHttp\Command\Command))
#2 C:\server\www\wporg-client\vendor\guzzlehttp\command\src\ServiceClient.php(153): GuzzleHttp\Command\ServiceClient->execute(Object(GuzzleHttp\Command\Command))
#3 C:\server\www\wporg-client\php\WporgClient.php(172): GuzzleHttp\Command\ServiceClient->__call('getPluginsInfo', Array)
#4 C:\server\www\wporg-client\test.php(36): Rarst\Guzzle\WporgClient->getPlugin('english-wp-admi...', Array)
#5 {main in C:\server\www\wporg-client\vendor\guzzlehttp\guzzle-services\src\Handler\ValidatedDescriptionHandler.php on line 76
```

However if I change `type` to `string` I get another error, since it now _casts_ (?) input to string and I give it array (which my filter expects):

```
Fatal error: Uncaught TypeError: Argument 1 passed to Rarst\Guzzle\WporgClient::toObject() must be of the type array, string given in C:\server\www\wporg-client\php\WporgClient.php:56
Stack trace:
#0 [internal function]: Rarst\Guzzle\WporgClient::toObject('O:8:"stdClass":...')
#1 C:\server\www\wporg-client\vendor\guzzlehttp\guzzle-services\src\Parameter.php(291): call_user_func('Rarst\\Guzzle\\Wp...', 'O:8:"stdClass":...')
#2 C:\server\www\wporg-client\vendor\guzzlehttp\guzzle-services\src\RequestLocation\AbstractLocation.php(65): GuzzleHttp\Command\Guzzle\Parameter->filter('O:8:"stdClass":...')
#3 C:\server\www\wporg-client\vendor\guzzlehttp\guzzle-services\src\RequestLocation\FormParamLocation.php(44): GuzzleHttp\Command\Guzzle\RequestLocation\AbstractLocation->prepareValue('O:8:"stdClass":...', Object(GuzzleHttp\Command\Guzzle\Parameter))
#4 C:\server\www\wporg-client\vendor\guzzlehttp\guzzle-services\src\Serializer.php(90): GuzzleHttp\Command\Guzzle\RequestLocation\FormParamLocation->visit(Object(GuzzleHttp\Command\Co in C:\server\www\wporg-client\php\WporgClient.php on line 56
```

I don't see a way around this, short of ditching filters altogether and handling input externally? Which makes service description less useful/self-contained.

Hmmm, if I add a dumper to filters it seems that they are now (?) called _twice_ and once array is passed as is and another time it is cast to string?..

**Comment by Rarst** [comment]
Call stacks for the two calls with different behavior:

Description validation (doesn't cast array to string):

```
#0  Rarst\Guzzle\WporgService::Rarst\Guzzle\{closure}()
#1  call_user_func() called at [C:\server\www\wporg-client\vendor\guzzlehttp\guzzle-services\src\Parameter.php:291]
#2  GuzzleHttp\Command\Guzzle\Parameter->filter() called at [C:\server\www\wporg-client\vendor\guzzlehttp\guzzle-services\src\Handler\ValidatedDescriptionHandler.php:47]
#3  GuzzleHttp\Command\Guzzle\Handler\ValidatedDescriptionHandler->GuzzleHttp\Command\Guzzle\Handler\{closure}() called at [C:\server\www\wporg-client\vendor\guzzlehttp\command\src\ServiceClient.php:85]
#4  GuzzleHttp\Command\ServiceClient->executeAsync() called at [C:\server\www\wporg-client\vendor\guzzlehttp\command\src\ServiceClient.php:77]
#5  GuzzleHttp\Command\ServiceClient->execute() called at [C:\server\www\wporg-client\vendor\guzzlehttp\command\src\ServiceClient.php:153]
#6  GuzzleHttp\Command\ServiceClient->__call() called at [C:\server\www\wporg-client\php\WporgClient.php:172]
#7  Rarst\Guzzle\WporgClient->getPlugin() called at [C:\server\www\wporg-client\test.php:36]
```

Request preparation (does cast or something to string):

```
#0  Rarst\Guzzle\WporgService::Rarst\Guzzle\{closure}()
#1  call_user_func() called at [C:\server\www\wporg-client\vendor\guzzlehttp\guzzle-services\src\Parameter.php:291]
#2  GuzzleHttp\Command\Guzzle\Parameter->filter() called at [C:\server\www\wporg-client\vendor\guzzlehttp\guzzle-services\src\RequestLocation\AbstractLocation.php:65]
#3  GuzzleHttp\Command\Guzzle\RequestLocation\AbstractLocation->prepareValue() called at
[C:\server\www\wporg-client\vendor\guzzlehttp\guzzle-services\src\RequestLocation\FormParamLocation.php:44]
#4  GuzzleHttp\Command\Guzzle\RequestLocation\FormParamLocation->visit() called at [C:\server\www\wporg-client\vendor\guzzlehttp\guzzle-services\src\Serializer.php:90]
#5  GuzzleHttp\Command\Guzzle\Serializer->prepareRequest() called at [C:\server\www\wporg-client\vendor\guzzlehttp\guzzle-services\src\Serializer.php:60]
#6  GuzzleHttp\Command\Guzzle\Serializer->__invoke() called at [C:\server\www\wporg-client\vendor\guzzlehttp\command\src\ServiceClient.php:195]
#7  GuzzleHttp\Command\ServiceClient->transformCommandToRequest() called at [C:\server\www\wporg-client\vendor\guzzlehttp\command\src\ServiceClient.php:172]
#8  GuzzleHttp\Command\ServiceClient->GuzzleHttp\Command\{closure}()
#9  Generator->current() called at [C:\server\www\wporg-client\vendor\guzzlehttp\promises\src\Coroutine.php:68]
#10 GuzzleHttp\Promise\Coroutine->__construct() called at [C:\server\www\wporg-client\vendor\guzzlehttp\promises\src\functions.php:456]
#11 GuzzleHttp\Promise\coroutine() called at [C:\server\www\wporg-client\vendor\guzzlehttp\command\src\ServiceClient.php:181]
#12 GuzzleHttp\Command\ServiceClient->GuzzleHttp\Command\{closure}() called at [C:\server\www\wporg-client\vendor\guzzlehttp\guzzle-services\src\Handler\ValidatedDescriptionHandler.php:79]
#13 GuzzleHttp\Command\Guzzle\Handler\ValidatedDescriptionHandler->GuzzleHttp\Command\Guzzle\Handler\{closure}() called at [C:\server\www\wporg-client\vendor\guzzlehttp\command\src\ServiceClient.php:85]
#14 GuzzleHttp\Command\ServiceClient->executeAsync() called at [C:\server\www\wporg-client\vendor\guzzlehttp\command\src\ServiceClient.php:77]
#15 GuzzleHttp\Command\ServiceClient->execute() called at [C:\server\www\wporg-client\vendor\guzzlehttp\command\src\ServiceClient.php:153]
#16 GuzzleHttp\Command\ServiceClient->__call() called at [C:\server\www\wporg-client\php\WporgClient.php:172]
#17 Rarst\Guzzle\WporgClient->getPlugin() called at [C:\server\www\wporg-client\test.php:36]
```

**Comment by Rarst** [comment]
I've moved on to a new API versions that don't need these filters, so unblocked on update and unlikely to follow up.
