### ISSUE TITLE
PUT requests with parameters with location of "postField" result in Exception

### ISSUE THREAD

**Issue by tomfotherby** [guzzle/guzzle-services#78]
I'm using v0.5 of this service. I have a _Service Description_ with a operation that uses `'httpMethod' => 'PUT'`:

``` php
$api = new GuzzleHttp\Command\Guzzle\Description([
            'baseUrl' => $myBaseUrl,
            'operations' => [
                'SubscriberChangeEmail' => [
                    'httpMethod' => 'PUT',
                    'uri' => '/myapp/api/subscriber/changeEmail',
                    'responseModel' => 'changeEmailOutput',
                    'parameters' => [
                        'oldEmail' => [
                            'location' => 'postField',
                        ],
                        'newEmail' => [
                            'location' => 'postField',
                        ],
                    ],
                ],
                ...

```

When I try to consume the API I get an exception due to my use of `'location' => 'postField'`:

```
exception 'RuntimeException' with message 'Must be a POST body interface' in /var/www/apisupertasker/vendor/guzzlehttp/guzzle-services/src/RequestLocation/PostFieldLocation.php:23
Stack trace:
#0 /var/www/apisupertasker/vendor/guzzlehttp/guzzle-services/src/Serializer.php(94): GuzzleHttp\Command\Guzzle\RequestLocation\PostFieldLocation->visit(Object(GuzzleHttp\Command\Command), Object(GuzzleHttp\Message\Request), Object(GuzzleHttp\Command\Guzzle\Parameter), Array)
#1 /var/www/apisupertasker/vendor/guzzlehttp/guzzle-services/src/Serializer.php(57): GuzzleHttp\Command\Guzzle\Serializer->prepareRequest(Object(GuzzleHttp\Command\CommandTransaction), Object(GuzzleHttp\Message\Request))
#2 /var/www/apisupertasker/vendor/guzzlehttp/guzzle-services/src/GuzzleClient.php(101): GuzzleHttp\Command\Guzzle\Serializer->__invoke(Object(GuzzleHttp\Command\CommandTransaction))
#3 /var/www/apisupertasker/vendor/guzzlehttp/command/src/AbstractClient.php(221): GuzzleHttp\Command\Guzzle\GuzzleClient->serializeRequest(Object(GuzzleHttp\Command\CommandTransaction))
#4 /var/www/apisupertasker/vendor/guzzlehttp/command/src/AbstractClient.php(81): GuzzleHttp\Command\AbstractClient->initTransaction(Object(GuzzleHttp\Command\Command))
#5 /var/www/apisupertasker/vendor/guzzlehttp/command/src/AbstractClient.php(76): GuzzleHttp\Command\AbstractClient->execute(Object(GuzzleHttp\Command\Command))
```

I tried `'location' => 'putField'` but that didn't work. I think this was fixed in a previous incarnation of the code, see https://github.com/guzzle/guzzle/issues/278 (but this is in a different git repo - I'm pretty confused about the versions, please excuse me for that :confused: ).

**Comment by JLGouwy** [comment]
I have the same problem with Method Patch and location postfield.

I use guzzle 5.0 & service 0.4.*

**Comment by Konafets** [comment]
I will close this issue. If your problem still exist with latest versions of Guzzle and Guzzle Service, feel free to reopen it.
